cadastro = []
nome = input("Insira seu nome: ")
cadastro.append(nome.title())
sobrenome = input("Insira seu sobrenome: ")
cadastro.append(sobrenome.title())
idade = int(input("Insira sua idade: "))
cadastro.append(idade)
nascimento =int(input("Insira sua data de nascimento: "))
cadastro.append( nascimento)
CPF = int(input("Insira seu CPF: "))
cadastro.append (CPF)
email = int(input("Insira o seu email: "))
cadastro.append (email)
print (cadastro)
